CREATE TABLE users(
	id_user SERIAL NOT NULL CONSTRAINT user_pkey PRIMARY KEY,
	email VARCHAR(150) NOT NULL,
	name VARCHAR(100) NOT NULL,
	pass VARCHAR(32) NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
) with(
oids=false
);